// Data class representing the response received from the Perplexity API.
data class PerplexityResponse(

    // List of Choice objects containing the options and their corresponding scores.
    val choices: List<Choice>,

    // The timestamp when the response was created by the Perplexity API.
    val created: Int,

    // Unique identifier for the response generated by the Perplexity API.
    val id: String,

    // The model used by the Perplexity API to generate the response.
    val model: String,

    // The type of object returned in the response. In this case, it is always "list".
    val `object`: String,

    // Object containing usage statistics for the API request, such as the number of tokens used.
    val usage: Usage
)

// Data class representing a single Choice object within the PerplexityResponse.
data class Choice(

    // The text content of the choice.
    val text: String,

    // The score associated with the choice, representing its relevance or probability.
    val score: Double,

    // Index of the choice within the list of choices, starting from 0.
    val index: Int
)

// Data class representing usage statistics for the Perplexity API request.
data class Usage(

    // The total number of tokens used in the API request.
    val total_tokens: Int,

    // The number of tokens used in the prompt of the API request.
    val prompt_tokens: Int,

    // The number of tokens used in the completion of the API request.
    val completion_tokens: Int,

    // The number of tokens that were free of charge in the API request.
    val free_tokens: Int
)
