// Data class representing the response received from the Perplexity API.
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder("choices", "created", "id", "model", "object", "usage")
data class PerplexityResponse(

    // List of Choice objects containing the options and their corresponding scores.
    @JsonProperty("choices")
    val choices: List<Choice>,

    // The timestamp when the response was created by the Perplexity API.
    @JsonProperty("created")
    val created: Int,

    // Unique identifier for the response generated by the Perplexity API.
    @JsonProperty("id")
    val id: String,

    // The model used by the Perplexity API to generate the response.
    @JsonProperty("model")
    val model: String,

    // The type of object returned in the response. In this case, it is always "list".
    @JsonProperty("object")
    val obj: String, // Renamed to `obj` to follow Kotlin naming conventions

    // Object containing usage statistics for the API request, such as the number of tokens used.
    @JsonProperty("usage")
    val usage: Usage
)

// Data class representing a single Choice object within the PerplexityResponse.
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder("text", "score", "index")
data class Choice(

    // The text content of the choice.
    @JsonProperty("text")
    val text: String,

    // The score associated with the choice, representing its relevance or probability.
    @JsonProperty("score")
    val score: Double,

    // Index of the choice within the list of choices, starting from 0.
    @JsonProperty("index")
    val index: Int
)

// Data class representing usage statistics for the Perplexity API request.
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder("total_tokens", "prompt_tokens", "completion_tokens", "free_tokens")
data class Usage(

    // The total number of tokens used in the API request.
    @JsonProperty("total_tokens")
    val totalTokens: Int, // Renamed to `totalTokens` to follow Kotlin naming conventions

    // The number of tokens used in the prompt of the API request.
    @JsonProperty("prompt_tokens")
    val promptTokens: Int, // Renamed to `promptTokens` to follow Kotlin naming conventions

    // The number of tokens used in the completion of the API request.
   
